parameterized spark compatible build
opendatadiscovery/oddrn-generator-java pull request #11
Opened 2022-01-25 09:39 UTC by dliubimov

2022-01-25 09:44 UTC, DementevNikita commented on build.gradle
> +                artifactId = 'oddrn-generator-java'
@dliubimov
should we make it 'oddrn-generator-java11' then?
what's the best practice for naming here?

2022-01-27 09:31 UTC, germanosin requested changes

2022-01-27 09:31 UTC, germanosin commented on build.gradle
> +    spark_compatible = findProperty('spark_compatible') ?: false
let's name it java8 compatibale)

2022-01-27 09:38 UTC, dliubimov commented on build.gradle
> +    spark_compatible = findProperty('spark_compatible') ?: false
done

2022-01-27 17:40 UTC, DementevNikita commented
@dliubimov 

it also would be great if you could fix the linter errors (`gradle checkstyleMain`)

2022-01-28 06:48 UTC, dliubimov commented
> 

@DementevNikita done

2022-01-28 07:55 UTC, DementevNikita approved these changes

2022-01-28 09:02 UTC, germanosin approved these changes

2022-01-28 09:37 UTC, merged